# This is the configuration of your book-making machine.
# To store book metadata, rather use the _data folder.

# ------------------------------
# UPDATE THESE SETTINGS ON SETUP
# ------------------------------

# The primary language used in this series. You can set the language for each book individually below at 'defaults'. 
# To understand what language tags to use, read: http://www.w3.org/International/articles/language-tags/ 
# For the registry of tags: http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry 
# Useful lookup tool: http://r12a.github.io/apps/subtags/
language: en

# Are you importing a gem-based theme? By default we do not.
# If you are, remove the # before `theme:` and enter your theme's gem name.
# If you're using GitHub Pages, note that it may not support your theme.
# theme: your-theme-gem-name-here

# Which edition are we creating? You can leave this as `default`.
# This can be used to create different editions of a book using Liquid control-flow tags, 
# e.g. in includes, layouts and file-list
edition: "default"
#edition: ""

# To make absolute links work, e.g. in canonical links in <head>,
# include the url where this site will live when it's live (production).
canonical-url: "https://www.core-econ.org"

# If you're using GitHub Pages without a custom domain, make this
# the name of your repo, e.g. /electric-book
# It must start with a slash. Otherwise you can leave it blank.
# See http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/
baseurl: "/core-experiments"

# If you're publishing a website on GitHub Pages
# and want to ensure you're using a compatible setup,
# add username/repository here and uncomment/enable
# gem 'github-pages', group: :jekyll_plugins
# in this project's Gemfile.
repository: ""

# Web navigation source: select either files or nav
# files: navigation will be taken from the web files list in `meta.yml`
# nav: navigation will be taken from the web nav tree in `meta.yml` (allows submenu nesting)
nav-source: nav

# Enable MathJax to render mathematics. MathJax adds a large script to your pages,
# so this is off (false) by default. Change to true to load MathJax.
# See http://docs.mathjax.org/en/latest/configuration.html for details.
# MathJax scripts are loaded by mathjax-config include, where you can also
# configure MathJax for your series.
mathjax-enabled: true

# Documentation
# These docs build along with your books, so they are available
# as you work. To turn off the docs, change output to false.
collections:
  docs:
    output: false

# --------------------------------------------
# CHANGE THESE SETTINGS ONLY IF/WHEN NECESSARY
# --------------------------------------------

# Output different HTML structures based on intent.
# You can change these here, or rather override by loading two config files at the command line, e.g.:
# jekyll build -c _config.yml,_config.epub.yml
# output: "print-pdf"
output: "web"
# output: "epub"
# output: "screen-pdf"
# output: "lightning-source-colour"

# You can switch between sets of images for different purposes.
# For instance, small, colour images for epub and screen-pdf, 
# and high-res greyscale for print-pdf.
# Set your default image set here. This refers to the `images`
# directory in each book's directory, and then to any 
# subdirectories you create per set. Default is images/web,
# so that this works out of the box on GitHub Pages.
# image-set: "images"
# image-set: "images/epub"
image-set: "images/web"
# image-set: "images/print-pdf"
# image-set: "images/screen-pdf"

# Jekyll will ignore these files and folders. 
# Useful for temporarily speeding up processing for particular files
# Once your CSS is stable, exclude `css` here and keep it below under `keep_files`.
# Include the file extension too. E.g. book/text/01.md
exclude:
  # Build tools
  - CHANGELOG*
  - CNAME
  - eslint.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE*
  - node_modules
  - package-lock.json
  - package.json
  - README*
  - run-linux*
  - run-mac*
  - run-windows*
  - .sass-cache
  # Scripts we only want the minified versions of
  - /assets/js/nav.js
  - /assets/js/get-query-variable.js
  - /assets/js/mark-search-terms.js
  - /assets/js/slides.js
  - /assets/js/lazyload.js
  - /assets/js/videos.js
  - /assets/js/accordions.js
  - /assets/js/tables.js
  - /assets/js/new-tabs.js
  - /assets/js/definitions.js
  - /assets/js/footnotes.js
  - /assets/js/mcqs.js
  # We don't need these because they are
  # include_relative'd in bundle.js and bundle-search.js
  - /assets/js/accordions.min.js
  - /assets/js/annotation.js
  - /assets/js/annotation.min.js
  - /assets/js/bookmarks.js
  - /assets/js/definitions.min.js
  - /assets/js/elasticlunr.min.js
  - /assets/js/footnotes.min.js
  - /assets/js/get-query-variable.min.js
  - /assets/js/google-cse.js
  - /assets/js/lazyload.min.js
  - /assets/js/locales.js
  - /assets/js/mark-search-terms.min.js
  - /assets/js/mark.min.js
  - /assets/js/mcqs.min.js
  - /assets/js/metadata.js
  - /assets/js/nav.min.js
  - /assets/js/new-tabs.min.js
  - /assets/js/polyfills.min.js
  - /assets/js/search-data.js
  - /assets/js/search.min.js
  - /assets/js/slides.min.js
  - /assets/js/tables.min.js
  - /assets/js/toggle-expandable-box.min.js
  - /assets/js/utilities.js
  - /assets/js/videos.min.js
  # Files we don't need for default, web output
  - /assets/profiles
  - /assets/js/bump.js
  - /assets/js/footnotes_pdf.js
  - /assets/js/footnotes_pdf.min.js
  - /assets/js/heading-titles.js
  - /assets/js/heading-titles.min.js
  - /assets/js/images-only.js
  - /assets/js/page-reference.js
  - /assets/js/render-mathjax.js
  - /*/package.opf
  - /*/fonts
  - /*/images/print-pdf
  - /*/images/screen-pdf
  - /*/images/epub
  - /*/images/app
  - /*/styles/app*
  - /*/styles/print-pdf*
  - /*/styles/screen-pdf*
  - /*/styles/epub*
  # -----------------------------------
  # Book files
  # -----------------------------------
  # - search*
  # - /*/images/web
  # - /*/fonts
  # - /*/styles
  # - /*/text/0-0-cover*
  # - /*/text/0-1-0-halftitlepage*
  # - /*/text/0-1-titlepage*
  # - /*/text/0-2-copyright*
  # - /*/text/0-3-contents*
  # - /*/text/0-4-preface*
  # - /*/text/0-5-note-to-instructors*
  # - /*/text/0-6-contributors*
  # - /*/text/01*
  # - /*/text/02*
  # - /*/text/03*
  # - /*/text/04*
  # - /*/text/05*
  # - /*/text/06*
  # - /*/text/07*
  # - /*/text/08*
  # - /*/text/09*
  # - /*/text/10*
  # - /*/text/11*
  # - /*/text/12*
  # - /*/text/13*
  # - /*/text/14*
  # - /*/text/15*
  # - /*/text/16*
  # - /*/text/17*
  # - /*/text/18*
  # - /*/text/19*
  # - /*/text/20*
  # - /*/text/21*
  # - /*/text/22*
  # - /*/text/50-01-looking-forward*
  # - /*/text/50-02-glossary*
  # - /*/text/50-03-bibliography*
  # - /*/text/50-04-copyright-acknowledgements*
  # - /*/text/50-05-index*
  # - /*/text/search*
  # - /*/text/glossary*
  # - /*/text/question*
  # - /*/text/quiz*
  # ---------------------------------
  # English book
  # ---------------------------------
  # - /book/text/
  # ---------------------------------
  # French book
  # ---------------------------------
  # - /*/fr
  # - /*/fr/text/01*
  # ---------------------------------
  # Farsi book
  # ---------------------------------
  # - /*/fa
  # ------------------------
  # Table of questions
  # ------------------------
  # - /*/table-of-questions*
  # ---------------------------------
  # Italian book
  # ---------------------------------
  # - /*/it
  # ---------------------------------
  # Spanish book
  # ---------------------------------
  # - /*/es
  # ---------------------------------
# Can be useful to stop Jekyll overwriting files in _site.
# E.g. generate CSS once, then exclude above but keep here
# to make content regeneration faster.
# The file path is relative to the site.output directory.
keep_files:
  # -----------------------------------
  # Book files
  # -----------------------------------
  # - book/images/print-pdf
  # - book/images/screen-pdf
  # - book/images/web
  # - book/images/epub
  # - book/images/app
  # - book/fonts
  # - book/styles
  # - book/text
  # - book/text/0-0-cover.html
  # - book/text/0-1-0-halftitlepage.html
  # - book/text/0-1-titlepage.html
  # - book/text/0-2-copyright.html
  # - book/text/0-3-contents.html
  # - book/text/0-4-preface.html
  # - book/text/0-5-note-to-instructors.html
  # - book/text/0-6-contributors.html
  # - book/text/01.html
  # - book/text/02.html
  # - book/text/03.html
  # - book/text/04.html
  # - book/text/05.html
  # - book/text/06.html
  # - book/text/07.html
  # - book/text/08.html
  # - book/text/09.html
  # - book/text/10.html
  # - book/text/11.html
  # - book/text/12.html
  # - book/text/13.html
  # - book/text/14.html
  # - book/text/15.html
  # - book/text/16.html
  # - book/text/17.html
  # - book/text/18.html
  # - book/text/19.html
  # - book/text/20.html
  # - book/text/21.html
  # - book/text/22.html
  # - book/text/50-01-looking-forward.html
  # - book/text/50-02-glossary.html
  # - book/text/50-03-bibliography.html
  # - book/text/50-04-copyright-acknowledgements.html
  # - book/text/50-05-index.html
  # ------------------------
  # Table of questions
  # ------------------------
  # - book/text/table-of-questions.html

# Configure HTML compression
# See https://github.com/penibelst/jekyll-compress-html
compress_html:
  blanklines: true

# ----------------------------
# DO NOT CHANGE THESE SETTINGS
# ----------------------------

# Version of this Electric Book template
version: "0.7.0"

# Leave this unchanged as http://localhost:4000 unless you really know what you're doing here. This is the URL that Jekyll will run at by default locally.
url: http://localhost:4000

# Leave this unchanged as kramdown unless you really know how and why to change your markdown processor
markdown: kramdown

# kramdown options (see http://kramdown.gettalong.org/options.html)
# auto_id_stripping remove formatting from headings before generating IDs
# which keeps your IDs neat and tidy, and links persistent even if you format headings
kramdown:
  auto_id_stripping: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: r

# Leave this unchanged as none. This way, your book's chapters will all generate correctly named in one folder.
# This is really useful for grabbing all your HTML files at once for including in epubs or sending to PrinceXML.
permalink: none

# Leave this unchanged. It tells Jekyll where to find Sass partials
# (see http://jekyllrb.com/docs/assets/#sassscss)
# and whether to compress stylesheets
sass:
  sass_dir: _sass
  style: compressed

# Set default values here for all documents/pages in this publication. 
# (For technical details, see http://jekyllrb.com/docs/configuration/#front-matter-defaults).
# Store only site configurations here, and book metadata (title, author, ISBNs) in _data/meta.yml
defaults: 
  -
    scope: # Sets default page frontmatter for all files in this series (an empty string "" for path means all files).
      path: ""
    values:
      layout: "default"
      style: "chapter"
      stylesheet-print-pdf: "print-pdf.css"
      stylesheet-screen-pdf: "screen-pdf.css"
      stylesheet-web: "web.css"
      stylesheet-epub: "epub.css"
