audience: "students"
baseurl: "/experiencing-economics"
exclude:
  - book/text/50-01-other-experiments*
  - README*
  - run-linux*
  - run-mac*
  - run-windows*
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - eslint.json
  - /*/images/source
  # -----------------------------------
  # Colour profiles for conversions
  # -----------------------------------
  - /assets/profiles
  # -----------------------------------
  # Scripts we only want the minified versions of
  # -----------------------------------
  - /assets/js/nav.js
  - /assets/js/get-query-variable.js
  - /assets/js/mark-search-terms.js
  - /assets/js/slides.js
  - /assets/js/lazyload.js
  - /assets/js/videos.js
  - /assets/js/accordions.js
  - /assets/js/tables.js
  - /assets/js/new-tabs.js
  - /assets/js/definitions.js
  - /assets/js/footnotes.js
  - /assets/js/mcqs.js
  # We don't need these because they are
  # include_relative'd in bundle.js and bundle-search.js
  - /assets/js/accordions.min.js
  - /assets/js/annotation.js
  - /assets/js/annotation.min.js
  - /assets/js/definitions.min.js
  - /assets/js/elasticlunr.min.js
  - /assets/js/footnotes.min.js
  - /assets/js/get-query-variable.min.js
  - /assets/js/google-cse.js
  - /assets/js/lazyload.min.js
  - /assets/js/locales.js
  - /assets/js/mark-search-terms.min.js
  - /assets/js/mark.min.js
  - /assets/js/mcqs.min.js
  - /assets/js/metadata.js
  - /assets/js/nav.min.js
  - /assets/js/new-tabs.min.js
  - /assets/js/polyfills.min.js
  - /assets/js/search-data.js
  - /assets/js/search.min.js
  - /assets/js/slides.min.js
  - /assets/js/tables.min.js
  - /assets/js/toggle-expandable-box.min.js
  - /assets/js/videos.min.js
  # -----------------------------------
  # Scripts we don't need for web output
  # -----------------------------------
  - /assets/js/bump.js
  - /assets/js/footnotes_pdf.js
  - /assets/js/footnotes_pdf.min.js
  - /assets/js/heading-titles.js
  - /assets/js/heading-titles.min.js
  - /assets/js/images-only.js
  - /assets/js/page-reference.js
  - /assets/js/render-mathjax.js
  # -----------------------------------
  # Book files we don't need for web
  # -----------------------------------
  - /*/images/print-pdf
  - /*/images/screen-pdf
  - /*/images/epub
  - /*/images/app
  - /*/fonts
  - /*/styles/epub*
  - /*/styles/print-pdf*
  - /*/styles/screen-pdf*
  - /*/styles/app*
  - /*/styles/hyphenation*
  - /*/text/file-list
  - /*/package.opf
  # -----------------------------------
  # Book files we don't need for live
  # -----------------------------------
  - /*/text/table-of-questions*
  # -----------------------------------
  # Exclude web images only if you keep_files them below
  # -----------------------------------
  # /*/images/web,
  # -----------------------------------
  # Exclude translations not ready for prime time
  # -----------------------------------
  - /*/fa
  # - /*/it
