name: Deployment workflow
on:
    push:
        tags: "preview-deploy-test*"
jobs:
    deploy-student-site:
        name: Deploy student site
        runs-on: ubuntu-latest
        if: contains(github.ref, 'tags/preview-deploy-test')
        steps:
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.SSH_PRIVATE_KEY }} 
                known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
            
            - name: Adding Known Hosts
              run: ssh-keyscan -p 2222 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            
            - uses: actions/checkout@v3
              with:
                fetch-depth: 2
            
            - name: Set up Ruby 2.6
              uses: actions/setup-ruby@v1
              with:
                ruby-version: 2.7
            
            - name: Install Bundler
              run: gem install bundler
            
            - name: Bundle install
              run: bundle install
            
            - name: Run test script
              run: |
                chmod +x ./test.sh
                ./test.sh
            
            - name: Run deploy script
              env:
                  DEPLOY_METHOD_PREVIEWS: ${{ secrets.DEPLOY_METHOD_PREVIEWS }}
                  DESTINATIONPATH_PREVIEWS: ${{ secrets.DESTINATIONPATH_PREVIEWS }}
                  SSH_PREVIEWS: ${{ secrets.SSH_PREVIEWS }}
                  SSH_PREVIEWS_PORT: ${{ secrets.SSH_PREVIEWS_PORT }}
              run: |
                chmod +x ./deploy.sh
                ./deploy.sh
